import type { ILoadOptionsFunctions, INodeListSearchResult } from 'n8n-workflow';
import { createClient } from '../../../shared/infrastructure/paperless-client';
import type { TaxonomyDescriptor } from '../domain/taxonomy';

const PAGE_SIZE = 100;

/**
 * One page per call, filtered by the server. `name__icontains` is generated by
 * django-filter from `CHAR_KWARGS = ["istartswith", "iendswith", "icontains",
 * "iexact"]`, which every MatchingModel FilterSet declares for `name`
 * (`src/documents/filters.py`).
 */
export async function searchTaxonomy(
	ctx: ILoadOptionsFunctions,
	descriptor: TaxonomyDescriptor,
	filter?: string,
	paginationToken?: string,
): Promise<INodeListSearchResult> {
	const client = await createClient(ctx);
	const page = paginationToken === undefined ? 1 : Number(paginationToken);
	const { items, hasMore } = await client.requestPage<{ id: number; name: string }>({
		method: 'GET',
		path: descriptor.endpoint,
		qs: {
			ordering: 'name',
			page,
			page_size: PAGE_SIZE,
			// Empty rather than absent is what an untouched search box sends, and
			// django-filter would match it against every name.
			name__icontains: filter === undefined || filter === '' ? undefined : filter,
		},
	});

	return {
		results: items.map((entry) => ({ name: entry.name, value: String(entry.id) })),
		// n8n asks for the next page with this token; leaving it out ends the scroll.
		paginationToken: hasMore ? String(page + 1) : undefined,
	};
}
